services:
  postgres:
    image: postgres:16
    container_name: it_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
       - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    entrypoint: ["/bin/bash", "-c"]
    command: ["airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"]
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
    ##tell DAG to write artifacts
      ARTIFACT_STORE: s3
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: triage-artifacts
      S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

      # make sure boto3 is available inside airflow image
      PIP_ADDITIONAL_REQUIREMENTS: boto3

      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      INCIDENT_ARTIFACT_DIR: /opt/airflow/dags/artifacts
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      RUNBOOKS_DIR: /opt/airflow/runbooks
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/artifacts:/opt/airflow/dags/artifacts
      - ./runbooks:/opt/airflow/runbooks:ro

  airflow-scheduler:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:

        ##tell DAG to write artifacts
      ARTIFACT_STORE: s3
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: triage-artifacts
      S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

      # make sure boto3 is available inside airflow image
      PIP_ADDITIONAL_REQUIREMENTS: boto3
      INCIDENT_ARTIFACT_DIR: /opt/airflow/dags/artifacts
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      RUNBOOKS_DIR: /opt/airflow/runbooks
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/artifacts:/opt/airflow/dags/artifacts
      - ./runbooks:/opt/airflow/runbooks:ro

  incident-triage-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it_mcp
    environment:

      ARTIFACT_STORE: s3
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: triage-artifacts
      S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AIRFLOW_ARTIFACT_DIR: /Users/Apple/Documents/Personal Projects/incident-triage-mcp/airflow/artifacts

      MCP_TRANSPORT: streamable-http
      AUDIT_PATH: /data/audit.jsonl
      MCP_HOST: 0.0.0.0
      MCP_PORT: "3333"
      AIRFLOW_BASE_URL: http://airflow-webserver:8080
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
      RUNBOOKS_DIR: /runbooks
    volumes:
      - ./data:/data
      - ./airflow/artifacts:/airflow_artifacts
      - ./runbooks:/runbooks:ro
    ports:
      - "3333:3333"
    depends_on:
      airflow-webserver:
        condition: service_started


  minio:
    image: minio/minio:latest
    container_name: it_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: it_minio_init
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      "
      sleep 2;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/triage-artifacts || true;
      mc anonymous set download local/triage-artifacts || true;
      echo 'MinIO bucket ready';
      "
volumes:
  postgres_data:
  minio_data:
