services:
  postgres:
    image: postgres:16
    container_name: it_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
       - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 20

  airflow-init:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    entrypoint: ["/bin/bash", "-c"]
    command: ["airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"]
    restart: "no"

  airflow-webserver:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      INCIDENT_ARTIFACT_DIR: /opt/airflow/dags/artifacts
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/artifacts:/opt/airflow/dags/artifacts

  airflow-scheduler:
    image: apache/airflow:2.9.0-python3.11
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      INCIDENT_ARTIFACT_DIR: /opt/airflow/dags/artifacts
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/artifacts:/opt/airflow/dags/artifacts

  incident-triage-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it_mcp
    environment:
      AIRFLOW_ARTIFACT_DIR: /airflow_artifacts
      MCP_TRANSPORT: streamable-http
      AUDIT_PATH: /data/audit.jsonl
      MCP_HOST: 0.0.0.0
      MCP_PORT: "3333"
      AIRFLOW_BASE_URL: http://airflow-webserver:8080
    volumes:
      - ./data:/data
      - ./airflow/artifacts:/airflow_artifacts
    ports:
      - "3333:3333"
    depends_on:
      airflow-webserver:
        condition: service_started

volumes:
  postgres_data:
